title: Rui Wang
subtitle: 
    <center> Ph.D. Reserach Fellow </center>
    <center> Computer Science </center>
description: >- # this means to ignore newlines until "baseurl:"
  Personal Website of Rui Wang

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Biography
      url: /biography
    - text: Projects
      url: /blog
    - text: Publications
      url: /publications
    #- text: Gallery
    #  url: /gallery
    #- text: Shop
    #  url : /shop
    #- text: Contact Me
    #  url : /contact
    #- text: Styleguide
    #  url: /styleguide
    #- text: Get Started
    #  url: /get-started

# Edit these details

author_logo: profile.jpg
author: Rui Wang
author_bio: Rui Wang received M.Sc. in Computer Science and Engineering from Halmstad University, Sweden, 2014.
  He then worked as an IBM i software developer at the System & Technology Laboratory of the IBM Investment Company Limited until 2016.
  Currently, He is working as a Ph.D. research fellow in computer science at the Western Norway University of Applied Sciences (HVL). 
  His work and research interests include fault-tolerant distributed computing, distributed systems, software systems testing, model-based testing, 
  distributed algorithms, consensus protocols, concurrent and distributed software systems engineering, cloud computing, and internet-of-things.
author_email: "wruiwr86@gmail.com"
author_location: Bergen, Norway
author_website_url: "https://www.hvl.no/en/employee/?user=3612429"
author_scholar_url: "https://scholar.google.com/citations?user=4PkconcAAAAJ&hl=en"
author_cv_url:  "/assets/cv/classic-cv.pdf"
typewrite-text: Ph.D. Research Fellow in Computer Science.
  #at Western Norway University of Applied Sciences, Bergen, Norway.

author_work_experiences:
            - company_time: 03/2016-04/2020
              company_name: Western Norway University of Applied Sciences, Bergen, Norway
              #company_logo: google.png
              #company_url: https://google.com
              designation: Ph.D. Research Fellow in Computer Science - Software Engineering Group
              description: Worked on the research of model-based software testing for distriubted systems and consensus protocols.
              visibility: true
            - company_time: 08/2018-12/2018
              company_name: KTH Royal Institute of Technology, Stockholm, Sweden
              designation: Visiting Ph.D. Researcher - School of Electrical Engineering and Computer Science
              description: Research cooperation and worked on MBT techniques and the development of the Modbat Tester.
              visibility: true
            - company_time: 09/2015-02/2016
              company_name: IBM Investment Company LTD
              #company_logo: microsoft.png
              #company_url: https://microsoft.com
              designation: IBM i Software Developer - IBM System & Technology Laboratory
              description: Worked on the Common Information Model (CIM) project for IBM i System
              visibility: true
            - company_time: 06/2014-09/2014
              company_name: Halmstad university, Halmstad, Sweden
              designation: Research Assistant - Cyber-physical Systems Research Group
              description: Work on the development of 3D animations and visualizations for the Acumen simulation tool.
              visibility: true

author_other_experiences:
            - company_time: 08/2016-11/2019
              company_name: Western Norway University of Applied Sciences, Bergen, Norway
              designation: Teaching
              description: Bachelor courses - Basic Programming in Java; Mobile and Distributed Applications.
              visibility: true
            - company_time: 02/2017-05/2018
              company_name: Western Norway University of Applied Sciences, Bergen, Norway
              designation: Member of the Programme Committee for the Ph.D. Programme in Computer Science
              description: Attended committee meetings as a member of the Ph.D. programme committee, 
                            which involves all kinds of business for the Ph.D. programme in Computer Science, 
                            such as employment of research fellows, admission to the Ph.D. programme, 
                            budget for the Ph.D. programme, PhD courses, and research proposals.
              visibility: true

author_education_details:
              #- college_logo: mit.png
              - college_time: 2017-present
                college_name: Western Norway University of Applied Sciences, Bergen, Norway
              #  college_url: https://mit.org
                college_degree: Ph.D. in Computer Science - Software Engineering
                visibility: true
              - college_name: University of Stavanger, Stavanger, Norway
                college_time: 2017-2018
                college_degree: Ph.D. Project in Computer Science - Advanced Distributed Systems
                visibility: true
              - college_name: Halmstad University, Halmstad, Sweden
                college_time: 2011-2014
                college_degree: M.Sc in Computer Science and Engineering - Embedded and Intelligent Systems
                visibility: true


author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true
              - #project_thumbnail: hack4r.PNG
                project_title: test
                project_description: Test
                project_url: https://hack4r.com
                visibility: true

# social links
#twitter_username: johndoe
github_username:  wruiwr
#facebook_username: johndoe
linkedin_username: rui-wang-93bb0383
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
#hyvor_talk_website_id: 476

# wakatime username (coding activity)
#wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
#formspree_email: johndoe@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false
show_author_other_experiences: true

# algolia search
#algolia:
# application_id: D9WA1YKTRQ
#  index_name: blog_posts # You can replace that with whatever name you want
#  files_to_exclude: []
#  nodes_to_index: 'article'
#  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
#collections:
# - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
